### ISSUE TITLE
Republish on Maven Central

### ISSUE THREAD

**Issue by Xorlev** [Xorlev/grpc-jersey#17]
This artifact is no longer com.fullcontact, acquire a new namespace in Bintray or Sonatype.

**Comment by Xorlev** [comment]
Namespace acquired from Sonatype w/ central sync enabled.

Now available on central:
https://repo.maven.apache.org/maven2/com/xorlev/grpc-jersey/protoc-gen-jersey/

**Comment by Xorlev** [comment]
@gfecher 0.1.4 is now available on central. 0.1.4 includes your query parameter change as well as Windows support.

`com.xorlev` is the new artifact group id.

**Comment by gfecher** [comment]
Great, thanks again. I'll put it to good use tomorrow!
