### ISSUE TITLE
Default value in HttpHeaderContext field is not thread safe.

### ISSUE THREAD

**Issue by smartwjw** [Xorlev/grpc-jersey#26]
```
static final Context.Key<Multimap<String, String>> RESPONSE_HEADERS = Context
            .keyWithDefault("grpc-jersey-response-headers", HashMultimap.create());
```

Because `HashMultimap.create()` is called only once when the `RESPONSE_HEADERS` Key is construncting. And the `defaultValue` is shared across the whole JVM.

**Comment by smartwjw** [comment]
@Xorlev I've started a PR to fix this issue, please review if you have time.

**Comment by Xorlev** [comment]
Yep, you're absolutely right. 0.3.1 is releasing now.

Please feel free to open a second PR and add yourself to the CONTRIBUTORS.md file. :) Thanks so much @smartwjw.

**Comment by Xorlev** [comment]
0.3.1 released.
